# Generated by Django 4.2.25 on 2025-11-13 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='teacher',
            index=models.Index(fields=['first_name', 'last_name'], name='indx_first_last_name_teacher'),
        ),
    ]
