# Generated by Django 4.2.16 on 2025-11-13 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student', '0006_merge_20251024_1656'),
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('scolar_year', models.DecimalField(db_column='scolar_year', decimal_places=2, max_digits=10, primary_key=True, serialize=False)),
                ('date_note', models.DateTimeField(db_column='date_note')),
                ('value_note', models.DecimalField(db_column='value_note', decimal_places=2, max_digits=10)),
                ('id_sub', models.ForeignKey(db_column='id_sub', on_delete=django.db.models.deletion.CASCADE, to='subjects.subject')),
                ('id_type_eval', models.ForeignKey(db_column='id_type_eval', on_delete=django.db.models.deletion.CASCADE, to='subjects.tbtypeevaluation')),
                ('st_id', models.ForeignKey(db_column='st_id', on_delete=django.db.models.deletion.CASCADE, to='student.student')),
            ],
            options={
                'db_table': 'note',
            },
        ),
    ]
