# Generated by Django 4.2.16 on 2025-11-13 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='id_note',
            field=models.AutoField(
                auto_created=True, db_column='id_note', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='note',
            name='scolar_year',
            field=models.DecimalField(
                db_column='scolar_year', decimal_places=2, max_digits=10),
        ),
    ]
