# Generated by Django 4.2.16 on 2025-11-13 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_auto_20251113_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='id_note',
            field=models.AutoField(db_column='id_note', primary_key=True, serialize=False),
        ),
    ]
