# Generated by Django 4.2.16 on 2025-11-13 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_alter_note_id_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='scolar_year',
            field=models.PositiveIntegerField(db_column='scolar_year'),
        ),
    ]
