# Generated by Django 4.2.25 on 2025-11-13 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_alter_note_scolar_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='date_note',
            field=models.DateTimeField(db_column='date_note', db_index=True),
        ),
    ]
