# Generated by Django 4.2.25 on 2025-10-24 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_alter_parent_father_mobile_and_more'),
        ('student', '0005_populate_student_slugs'),
    ]

    operations = [
    ]
