# Generated by Django 4.2.25 on 2025-11-12 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TbTypeEvaluation',
            fields=[
                ('id_type_eval', models.AutoField(primary_key=True, serialize=False)),
                ('name_type_eval', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'tb_type_evaluation',
            },
        ),
        migrations.CreateModel(
            name='TbTypeSubject',
            fields=[
                ('id_type_sub', models.AutoField(primary_key=True, serialize=False)),
                ('name_type_sub', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'tb_type_subject',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id_sub', models.AutoField(primary_key=True, serialize=False)),
                ('name_sub', models.CharField(max_length=100)),
                ('coef_sub', models.DecimalField(decimal_places=2, max_digits=10)),
                ('id_teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='teachers.teacher')),
                ('id_type_sub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subjects.tbtypesubject')),
            ],
            options={
                'db_table': 'tb_subject',
            },
        ),
        migrations.CreateModel(
            name='Formation',
            fields=[
                ('format_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name_formation', models.CharField(max_length=100)),
                ('price_form', models.DecimalField(decimal_places=2, max_digits=10)),
                ('scolar_year', models.CharField(blank=True, max_length=100, null=True)),
                ('id_teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teachers.teacher')),
            ],
            options={
                'db_table': 'formation',
            },
        ),
    ]
