# Generated by Django 4.2.25 on 2025-11-13 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='name_sub',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='tbtypeevaluation',
            name='name_type_eval',
            field=models.CharField(db_index=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='tbtypesubject',
            name='name_type_sub',
            field=models.CharField(db_index=True, max_length=150),
        ),
    ]
