# Generated by Django 4.2.25 on 2025-11-09 22:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept_name', models.CharField(max_length=100, unique=True, verbose_name='Nom du département')),
                ('dept_code', models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='Code du département (ex: Dept01)')),
                ('dept_description', models.TextField(blank=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mis à jour le')),
                ('dept_location', models.CharField(blank=True, max_length=200, verbose_name='Emplacement (bâtiment, salle)')),
                ('dept_phone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone')),
                ('dept_email', models.EmailField(blank=True, max_length=254, verbose_name='Email de contact')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True, verbose_name='Slug')),
                ('dept_head', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='department_head', to='teachers.teacher', verbose_name='Chef de département')),
            ],
            options={
                'verbose_name': 'Département',
                'verbose_name_plural': 'Départements',
                'ordering': ['dept_name'],
            },
        ),
    ]
