# Generated by Django 4.2.25 on 2025-10-24 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='S5Dz5IEZy3m5iDZXqqDXWx8VwGNi0A4i', editable=False, max_length=32, unique=True),
        ),
    ]
