# Generated by Django 4.2.25 on 2025-10-24 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0003_alter_passwordresetrequest_token'),
    ]

    operations = [
        # Columns already added manually, marking as applied
    ]
