# Generated by Django 4.2.25 on 2025-10-24 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0004_auto_20251024_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='W2eh30D7sadd4DRBRtouTlwLPMkDwDzR', editable=False, max_length=32, unique=True),
        ),
    ]
