# Generated by Django 4.2.25 on 2025-10-24 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0005_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='SwW8wAE6dyW8dWwbpiax1MNE8rEZNgZs', editable=False, max_length=32, unique=True),
        ),
    ]
