# Generated by Django 4.2.25 on 2025-10-24 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0006_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='9sjVMz9MFBIz23CG1M1A5JNF5reejflj', editable=False, max_length=32, unique=True),
        ),
    ]
