# Generated by Django 4.2.25 on 2025-10-25 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0007_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='oSjwIjJ3zWpvI6N3excrxxRu1zQTKKsn', editable=False, max_length=32, unique=True),
        ),
    ]
