# Generated by Django 4.2.25 on 2025-10-25 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0008_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='R3fRN95J2tGu5oySf1IQQqSnNf2VHc91', editable=False, max_length=32, unique=True),
        ),
    ]
