# Generated by Django 4.2.25 on 2025-11-09 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0009_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='c3b8z5qG8bdHLYtahsoldOVjuguintNu', editable=False, max_length=32, unique=True),
        ),
    ]
