# Generated by Django 4.2.25 on 2025-11-11 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0010_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='417gcdMjJWpdESOBex8J2IPWKFXFXlx3', editable=False, max_length=32, unique=True),
        ),
    ]
