# Generated by Django 4.2.25 on 2025-11-12 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0011_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='IFUhNc2DohW9Xerhs4dBd7psqIr1EkVl', editable=False, max_length=32, unique=True),
        ),
    ]
