# Generated by Django 4.2.25 on 2025-11-12 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0012_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='W2Jdl7ofEHWoBMZNphiZ6lxwvBr7s2bB', editable=False, max_length=32, unique=True),
        ),
    ]
