# Generated by Django 4.2.25 on 2025-11-13 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0015_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='beJMoS7p6X3NcezwIlqsCPPWrpWMiSpk', editable=False, max_length=32, unique=True),
        ),
    ]
