# Generated by Django 4.2.16 on 2025-11-15 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0016_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='iAY5mbBwnkAifCljyDnVs7O8iOaABT6H', editable=False, max_length=32, unique=True),
        ),
    ]
